app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(navbar = "Local skills")
app$setInputs(GeoType = "LSIP")
app$setInputs(lep1 = "Cambridgeshire and Peterborough")
app$setInputs(lep1 = "Hull and East Yorkshire")
app$setInputs(EmpOcc_rows_current = c(5, 3, 1, 4, 2), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_all = c(5, 3, 1, 4, 2), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_state = c(1667466022244, 0, 10, 2, "desc", "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(GeoType = "LEP")
app$setInputs(lep1 = "Greater Manchester")
app$setInputs(lep2 = "Cheshire and Warrington")
app$setInputs(lep2 = "Lancashire")
app$setInputs(datatabset = "Vacancies")
app$setInputs(datatabset = "Employment")
app$setInputs(`plotly_afterplot-A` = "\"EmpRate_time\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":530,\"height\":400}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_afterplot-A` = "\"EmpRate_time\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":679,\"height\":400}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(EmpOcc_rows_current = c(14, 9, 8, 19, 17, 7, 13, 24, 21, 22), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_all = c(14, 9, 8, 19, 17, 7, 13, 24, 21, 22, 10, 16, 2, 15, 23, 4, 20, 5, 6, 18, 25, 3, 1, 11, 12), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_state = c(1667466045771, 0, 10, c("1", "asc"), "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_current = c(12, 11, 1, 3, 25, 18, 6, 5, 20, 4), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_all = c(12, 11, 1, 3, 25, 18, 6, 5, 20, 4, 23, 15, 2, 16, 10, 22, 21, 24, 13, 7, 17, 19, 8, 9, 14), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_state = c(1667466048507, 0, 10, c("1", "desc"), "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_current = c(14, 9, 17, 21, 13, 24, 19, 7, 8, 10), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_all = c(14, 9, 17, 21, 13, 24, 19, 7, 8, 10, 22, 16, 15, 2, 23, 4, 5, 20, 6, 1, 18, 3, 11, 25, 12), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_state = c(1667466049743, 0, 10, c("2", "asc"), "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_current = c(12, 25, 11, 3, 18, 1, 6, 20, 5, 4), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_rows_all = c(12, 25, 11, 3, 18, 1, 6, 20, 5, 4, 23, 2, 15, 16, 22, 10, 8, 7, 19, 13, 24, 21, 17, 9, 14), allowInputNoBinding_ = TRUE)
app$setInputs(EmpOcc_state = c(1667466050533, 0, 10, c("2", "desc"), "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshotDownload("download_btn1a")
app$setInputs(datatabset = "Vacancies")
app$setInputs(`plotly_afterplot-A` = "\"jobad.time\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":1389,\"height\":400}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(lep1 = "Greater Cambridge and Greater Peterborough")
app$setInputs(GeoType = "LSIP")
app$setInputs(lep2 = "West Midlands and Warwickshire")
app$setInputs(lep2 = "West Yorkshire")
app$setInputs(`plotly_hover-A` = "[{\"curveNumber\":0,\"pointNumber\":2,\"x\":2019,\"y\":201.6}]", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = character(0), allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = "[{\"curveNumber\":1,\"pointNumber\":4,\"x\":2021,\"y\":188.2}]", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = character(0), allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = "[{\"curveNumber\":1,\"pointNumber\":1,\"x\":2018,\"y\":263.4}]", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = character(0), allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(datatabset = "Skills")
app$setInputs(skill_line = "Education and training (adults only)")
app$setInputs(skill_line = "Community learning (adults only)")
app$setInputs(`plotly_hover-A` = "[{\"curveNumber\":0,\"pointNumber\":0,\"x\":0.0651387213510253,\"y\":15.775}]", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = character(0), allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = "[{\"curveNumber\":1,\"pointNumber\":6,\"x\":0.206607236497116,\"y\":10.225}]", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = character(0), allowInputNoBinding_ = TRUE, priority_ = "event")
app$snapshotDownload("download_btn2b")
app$setInputs(`plotly_hover-A` = "[{\"curveNumber\":0,\"pointNumber\":13,\"x\":0.0301568154402895,\"y\":2.775}]", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_hover-A` = character(0), allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(navbar = "Data & downloads")
app$setInputs(DataTbl_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8), allowInputNoBinding_ = TRUE)
app$setInputs(DataTbl_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8), allowInputNoBinding_ = TRUE)
app$setInputs(DataTbl_state = c(1667466107339, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(DataTbl_rows_selected = 1, allowInputNoBinding_ = TRUE)
app$setInputs(DataTbl_row_last_clicked = 1, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(DataTbl_rows_selected = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(DataTbl_row_last_clicked = 2, allowInputNoBinding_ = TRUE, priority_ = "event")
app$snapshotDownload("downloadData2")
app$setInputs(navbar = "Accessibility")
app$setInputs(navbar = "Support and feedback")
app$setInputs(navbar = "Local skills")
app$setInputs(datatabset = "Overview")
app$setInputs(`plotly_afterplot-A` = "\"empLineChart\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_afterplot-A` = "\"empRateLineChart\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_afterplot-A` = "\"VacLineChart\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_afterplot-A` = "\"etLineChart\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_afterplot-A` = "\"AppLineChart\"", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":429,\"height\":81}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":429,\"height\":81}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":429,\"height\":81}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":429,\"height\":81}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`plotly_relayout-A` = "{\"width\":429,\"height\":81}", allowInputNoBinding_ = TRUE, priority_ = "event")
app$snapshot()
